ENUMFIELDS = {
	'03E3': {'length': 16, 'name': 'Salt'},

"""
	'0014': {'length': 'EnumBlockArray', 'name': 'Class Menu Content'},
	'0033': {'length': 'EnumBlockArray', 'name': False},
	'0035': {'length': 'EnumBlockArray', 'name': False},
	'003A': {'length': 'EnumBlockArray', 'name': False},
	'003D': {'length': 'EnumBlockArray', 'name': False},
	'0041': {'length': 'EnumBlockArray', 'name': False},
	'004C': {'length': 'EnumBlockArray', 'name': False},
	'006D': {'length': 'EnumBlockArray', 'name': False},
	'006F': {'length': 'EnumBlockArray', 'name': False},
	'0070': {'length': 'EnumBlockArray', 'name': 'Chat Message'},
	'0085': {'length': 'EnumBlockArray', 'name': False},
	'00B0': {'length': 'EnumBlockArray', 'name': False},
	'00B1': {'length': 'EnumBlockArray', 'name': 'Server Join Step 1'},
	'00B2': {'length': 'EnumBlockArray', 'name': 'Server Join Step 2'},
	'00B3': {'length': 'EnumBlockArray', 'name': 'Server Disconnect'},
	'00B4': {'length': 'EnumBlockArray', 'name': False},
	'00D5': {'length': 'EnumBlockArray', 'name': False},
	'00EC': {'length': 'EnumBlockArray', 'name': '/report Command'},
	'00FB': {'length': 'EnumBlockArray', 'name': False},
	'010F': {'length': 'EnumBlockArray', 'name': '(something to do with match end)'},
	'011B': {'length': 'EnumBlockArray', 'name': 'Player Online/Join Notification'},
	'011C': {'length': 'EnumBlockArray', 'name': False},
	'0145': {'length': 'EnumBlockArray', 'name': False},
	'0175': {'length': 'EnumBlockArray', 'name': 'Purchase'},
	'0176': {'length': 'EnumBlockArray', 'name': False},
	'0177': {'length': 'EnumBlockArray', 'name': False},
	'0182': {'length': 'EnumBlockArray', 'name': False},
	'0183': {'length': 'EnumBlockArray', 'name': False},
	'018A': {'length': 'EnumBlockArray', 'name': '/sc Command'},
	'018B': {'length': 'EnumBlockArray', 'name': False},
	'018C': {'length': 'EnumBlockArray', 'name': '/votekick Command'},
	'0197': {'length': 'EnumBlockArray', 'name': False},
	'019A': {'length': 'EnumBlockArray', 'name': '(something to do with match end)'},
	'01A2': {'length': 'EnumBlockArray', 'name': '(something to do with setting up a custom server)'},
	'01A4': {'length': 'EnumBlockArray', 'name': '(something to do with setting up a custom server)'},
	'01A5': {'length': 'EnumBlockArray', 'name': '(something to do with setting up a custom server)'},
	'01AB': {'length': 'EnumBlockArray', 'name': '(something to do with setting up a custom server)'},
	'01B5': {'length': 'EnumBlockArray', 'name': 'Watch-Now Menu Content'},
	'01BC': {'length': 'EnumBlockArray', 'name': False},
	'01C6': {'length': 'EnumBlockArray', 'name': False},
	'01C8': {'length': 'EnumBlockArray', 'name': False},
	'00E9': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'00FE': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0116': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0122': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0127': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0132': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0138': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0144': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0148': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'05CB': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0632': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0633': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'063E': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0662': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'067E': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'0681': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'068B': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'06BB': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
	'06EF': {'length': 'ArrayOfEnumBlockArrays', 'name': False},
"""

"""
	'0013': {'length': 'Sized', 'name': False},
	'0082': {'length': 'Sized', 'name': False},
	'00A2': {'length': 'Sized', 'name': False},
	'00A3': {'length': 'Sized', 'name': False},
	'00AA': {'length': 'Sized', 'name': False},
	'00AB': {'length': 'Sized', 'name': False},
	'01A4': {'length': 'Sized', 'name': 'MOTD / Report Text'},
	'01A6': {'length': 'Sized', 'name': False},
"""

"""
	'01BC': {'length': 'Sized', 'name': False},
"""

"""
	'01C4': {'length': 'Sized', 'name': False},
	'020C': {'length': 'Sized', 'name': False},
	'021A': {'length': 'Sized', 'name': 'Game Mode'},
	'0261': {'length': 'Sized', 'name': 'Integer-Valued Menu Option'},
	'026F': {'length': 'Sized', 'name': 'Purchase Name'},
	'02AF': {'length': 'Sized', 'name': False},
	'02B1': {'length': 'Sized', 'name': 'Internal Map Name'},
	'02B6': {'length': 'Sized', 'name': 'Map Name'},
	'02E6': {'length': 'Sized', 'name': 'Message Text'},
	'02FE': {'length': 'Sized', 'name': 'Sender Name/Clan Tag to Purchase'},
	'0300': {'length': 'Sized', 'name': 'Map + Gamemode, Server or Region Name'},
"""

	'034A': {'length': 'Sized', 'type': 'String', 'name': 'Player Name'},
	'035B': {'length': 'Sized', 'name': False},
	'037C': {'length': 'Sized', 'name': False},
	'0437': {'length': 'Sized', 'name': 'String-Valued Menu Option'},
	'045E': {'length': 'Sized', 'name': False},
	'0468': {'length': 'Sized', 'name': False},
	'0494': {'length': 'Sized', 'name': 'Login Name'},
	'063B': {'length': 'Sized', 'name': False},
	'0669': {'length': 'Sized', 'name': 'Promotion Code'},
	'06B8': {'length': 'Sized', 'name': False},
	'06DE': {'length': 'Sized', 'type': 'String', 'name': 'Clan Tag'},
	'06E9': {'length': 'Sized', 'name': False},
	'0705': {'length': 'Sized', 'name': 'Player Name of Kicker'},
	'0001': {'length': 1, 'name': False},
	'006F': {'length': 1, 'name': False},
	'01FA': {'length': 1, 'name': False},
	'02C9': {'length': 1, 'name': False},
	'0318': {'length': 1, 'name': False},
	'0326': {'length': 1, 'name': False},
	'0442': {'length': 1, 'name': False},
	'046B': {'length': 1, 'name': False},
	'0574': {'length': 1, 'name': False},
	'0592': {'length': 1, 'name': 'Player Vote'},
	'05D6': {'length': 1, 'name': False},
	'05E6': {'length': 1, 'name': False},
	'0601': {'length': 1, 'name': False},
	'063C': {'length': 1, 'name': False},
	'0673': {'length': 1, 'name': False},
	'069B': {'length': 1, 'name': False},
	'069C': {'length': 1, 'name': 'Password Required'},
	'0703': {'length': 1, 'name': False},
	'0307': {'length': 2, 'name': False},
	'053D': {'length': 2, 'name': 'Ping Time'},
	'0600': {'length': 2, 'name': False},

"""
	'006E': {'length': 3, 'name': False},

	'0019': {'length': 4, 'name': False},
	'0035': {'length': 4, 'name': 'Blood Eagle Score'},
	'006D': {'length': 4, 'name': False},
	'0073': {'length': 4, 'name': False},
	'008B': {'length': 4, 'name': False},
	'008D': {'length': 4, 'name': False},
	'0095': {'length': 4, 'name': False},
	'009D': {'length': 4, 'name': False},
	'009E': {'length': 4, 'name': 'Message Type (2=public, 3=team, 6=private)'},
	'00BA': {'length': 4, 'name': False},
	'00BF': {'length': 4, 'name': False},
	'00C3': {'length': 4, 'name': False},
	'00C6': {'length': 4, 'name': False},
	'00D4': {'length': 4, 'name': False},
	'0197': {'length': 4, 'name': 'Diamond Sword Score'},
"""
	'01A3': {'length': 4, 'name': False},
	'01C0': {'length': 4, 'name': False},
	'01C1': {'length': 4, 'name': False},
	'01C9': {'length': 4, 'name': False},
	'01E3': {'length': 4, 'name': False},
	'01E8': {'length': 4, 'name': False},
	'020B': {'length': 4, 'name': False},
	'020D': {'length': 4, 'name': False},
	'0219': {'length': 4, 'name': False},
	'021B': {'length': 4, 'name': False},
	'021F': {'length': 4, 'name': False},
	'0225': {'length': 4, 'name': False},
	'0228': {'length': 4, 'name': False},
	'0242': {'length': 4, 'name': False},
	'0253': {'length': 4, 'name': False},
	'0259': {'length': 4, 'name': False},
	'025A': {'length': 4, 'name': False},
	'025C': {'length': 4, 'name': False},
	'025D': {'length': 4, 'name': False},
	'025E': {'length': 4, 'name': False},
	'025F': {'length': 4, 'name': False},
	'0263': {'length': 4, 'name': False},
	'026D': {'length': 4, 'name': False},
	'0272': {'length': 4, 'name': False},
	'0273': {'length': 4, 'name': False},
	'0296': {'length': 4, 'name': 'Player Rank (unused)'},
	'0298': {'length': 4, 'name': False},
	'0299': {'length': 4, 'name': False},
	'02A3': {'length': 4, 'name': False},
	'02AB': {'length': 4, 'name': 'Purchase Type (1de=server, 1fc=boosters, 200=name, 221=tag)'},
	'02AC': {'length': 4, 'name': False},
	'02B2': {'length': 4, 'name': 'Map ID'},
	'02B3': {'length': 4, 'name': False},
	'02B5': {'length': 4, 'name': False},
	'02B7': {'length': 4, 'name': False},
	'02BE': {'length': 4, 'name': False},
	'02C4': {'length': 4, 'name': 'Match ID?'},
	'02C7': {'length': 4, 'name': 'Server ID'},
	'02D6': {'length': 4, 'name': False},
	'02D7': {'length': 4, 'name': False},
	'02D8': {'length': 4, 'name': False},
	'02DC': {'length': 4, 'name': False},
	'02EA': {'length': 4, 'name': False},
	'02EC': {'length': 4, 'name': False},
	'02ED': {'length': 4, 'name': False},
	'02EF': {'length': 4, 'name': False},
	'02F4': {'length': 4, 'name': 'Remaining Time in Seconds'},
	'02FC': {'length': 4, 'name': 'Std Message ID'},
	'02FF': {'length': 4, 'name': False},
	'0319': {'length': 4, 'name': False},
	'0320': {'length': 4, 'name': False},
	'0331': {'length': 4, 'name': False},
	'0333': {'length': 4, 'name': False},
	'0343': {'length': 4, 'name': False},
	'0344': {'length': 4, 'name': False},
	'0345': {'length': 4, 'name': False},
	'0346': {'length': 4, 'name': False},
	'0347': {'length': 4, 'name': False},
	'0348': {'length': 4, 'name': 'Player ID'},
	'035A': {'length': 4, 'name': 'Payment Amount'},
	'0363': {'length': 4, 'name': False},
	'0369': {'length': 4, 'name': 'Menu Option Identifier'},
	'036B': {'length': 4, 'name': False},
	'036C': {'length': 4, 'name': False},
	'037F': {'length': 4, 'name': False},
	'0380': {'length': 4, 'name': False},
	'0385': {'length': 4, 'name': False},
	'0398': {'length': 4, 'name': False},
	'03A4': {'length': 4, 'name': False},
	'03B4': {'length': 4, 'name': False},
	'03CE': {'length': 4, 'name': False},
	'03E0': {'length': 4, 'name': False},
	'03F1': {'length': 4, 'name': False},
	'03F5': {'length': 4, 'name': False},
	'03FD': {'length': 4, 'name': False},
	'041A': {'length': 4, 'name': False},
	'042A': {'length': 4, 'name': False},
	'042B': {'length': 4, 'name': False},
	'042E': {'length': 4, 'name': False},
	'042F': {'length': 4, 'name': False},
	'0448': {'length': 4, 'name': 'Region ID'},
	'0452': {'length': 4, 'name': 'Team ID'},
	'0457': {'length': 4, 'name': False},
	'0458': {'length': 4, 'name': False},
	'0472': {'length': 4, 'name': False},
	'0489': {'length': 4, 'name': False},
	'049E': {'length': 4, 'name': 'Version Number'},
	'04A5': {'length': 4, 'name': False},
	'04A6': {'length': 4, 'name': False},
	'04A7': {'length': 4, 'name': False},
	'04A8': {'length': 4, 'name': False},
	'04A9': {'length': 4, 'name': False},
	'04AA': {'length': 4, 'name': False},
	'04BB': {'length': 4, 'name': False},
	'04CB': {'length': 4, 'name': 'Player XP'},
	'04D1': {'length': 4, 'name': False},
	'04D5': {'length': 4, 'name': False},
	'04D9': {'length': 4, 'name': False},
	'04FA': {'length': 4, 'name': False},
	'0502': {'length': 4, 'name': False},
	'0556': {'length': 4, 'name': False},
	'0558': {'length': 4, 'name': False},
	'056A': {'length': 4, 'name': False},
	'0577': {'length': 4, 'name': False},
	'057D': {'length': 4, 'name': False},
	'057F': {'length': 4, 'name': False},
	'058A': {'length': 4, 'name': False},
	'0591': {'length': 4, 'name': False},
	'0596': {'length': 4, 'name': False},
	'0597': {'length': 4, 'name': False},
	'05B8': {'length': 4, 'name': False},
	'05CC': {'length': 4, 'name': 'Currency? (0x0645=gold, 0x27f9=xp)'},
	'05CF': {'length': 4, 'name': 'Purchase Seqnr'},
	'05D3': {'length': 4, 'name': 'Player Gold'},
	'05DC': {'length': 4, 'name': 'Player Rank Progress'},
	'05E9': {'length': 4, 'name': False},
	'05EA': {'length': 4, 'name': False},
	'05EE': {'length': 4, 'name': False},
	'0602': {'length': 4, 'name': False},
	'0608': {'length': 4, 'name': False},
	'060A': {'length': 4, 'name': False},
	'060C': {'length': 4, 'name': False},
	'0615': {'length': 4, 'name': False},
	'061D': {'length': 4, 'name': False},
	'0623': {'length': 4, 'name': False},
	'062D': {'length': 4, 'name': False},
	'062E': {'length': 4, 'name': False},
	'062F': {'length': 4, 'name': False},
	'0636': {'length': 4, 'name': False},
	'0637': {'length': 4, 'name': False},
	'0638': {'length': 4, 'name': False},
	'0639': {'length': 4, 'name': False},
	'063A': {'length': 4, 'name': False},
	'063D': {'length': 4, 'name': False},
	'065F': {'length': 4, 'name': False},
	'0660': {'length': 4, 'name': False},
	'0661': {'length': 4, 'name': False},
	'0663': {'length': 4, 'name': False},
	'0664': {'length': 4, 'name': False},
	'066A': {'length': 4, 'name': False},
	'0671': {'length': 4, 'name': False},
	'0672': {'length': 4, 'name': False},
	'0674': {'length': 4, 'name': False},
	'0675': {'length': 4, 'name': False},
	'0676': {'length': 4, 'name': False},
	'0677': {'length': 4, 'name': False},
	'067F': {'length': 4, 'name': False},
	'0680': {'length': 4, 'name': False},
	'0683': {'length': 4, 'name': False},
	'0684': {'length': 4, 'name': False},
	'068C': {'length': 4, 'name': False},
	'0698': {'length': 4, 'name': False},
	'0699': {'length': 4, 'name': False},
	'069D': {'length': 4, 'name': False},
	'069E': {'length': 4, 'name': False},
	'069F': {'length': 4, 'name': False},
	'06B7': {'length': 4, 'name': False},
	'06B9': {'length': 4, 'name': 'Watch-Now Section (1 = hirez news, 2 = twitch, 3 = training, 4 = community, 5 = ticker)'},
	'06BA': {'length': 4, 'name': '1 = featured, otherwise not featured'},
	'06BD': {'length': 4, 'name': False},
	'06BF': {'length': 4, 'name': False},
	'06C0': {'length': 4, 'name': False},
	'06C9': {'length': 4, 'name': False},
	'06EA': {'length': 4, 'name': False},
	'06EE': {'length': 4, 'name': False},
	'06F1': {'length': 4, 'name': False},
	'06F5': {'length': 4, 'name': False},
	'06FA': {'length': 4, 'name': False},
	'0701': {'length': 4, 'name': False},
	'0704': {'length': 4, 'name': 'Player ID of Kicker'},
	'0008': {'length': 8, 'name': False},
	'00B7': {'length': 8, 'name': False},
	'01D7': {'length': 8, 'name': False},
	'01F5': {'length': 8, 'name': False},
	'0246': {'length': 8, 'name': 'two bytes unknown + port + IP (9002 server)'},
	'024F': {'length': 8, 'name': 'two bytes unknown + port + IP (game server)'},
	'0303': {'length': 8, 'name': False},
	'0419': {'length': 8, 'name': False},
	'0434': {'length': 8, 'name': False},
	'04D4': {'length': 8, 'name': False},
	'057E': {'length': 8, 'name': False},
	'05E2': {'length': 8, 'name': False},
	'05E4': {'length': 8, 'name': False}
}